name: Split and Send Saved Video

on:
  workflow_dispatch:

jobs:
  split_process:
    runs-on: ubuntu-latest
    steps:
      # 1. تحميل الملف المخزن في GitHub
      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-5-minute-video

      # 2. تقسيم الفيديو تقنياً (بدون إعادة ترميز ليكون سريعاً جداً)
      - name: Split Video
        run: |
          # تقسيم الملف إلى جزءين (كل جزء 150 ثانية)
          # نستخدم -c copy لكي تتم العملية في ثانية واحدة فقط
          ffmpeg -i test_clip.mp4 -t 150 -c copy part1.mp4
          ffmpeg -i test_clip.mp4 -ss 150 -c copy part2.mp4

      # 3. إرسال الأجزاء إلى تليجرام
      - name: Send Parts to Telegram
        run: |
          # إرسال الجزء الأول
          curl -v -F "video=@part1.mp4" -F "caption=الجزء الأول (0:00 - 2:30)" \
          "https://api.telegram.org/bot8553237214:AAGnvhfyXa-B5Wkm3g_VQTRVbbr0ShyYM0U/sendVideo?chat_id=6849625315"
          
          # إرسال الجزء الثاني
          curl -v -F "video=@part2.mp4" -F "caption=الجزء الثاني (2:30 - 5:00)" \
          "https://api.telegram.org/bot8553237214:AAGnvhfyXa-B5Wkm3g_VQTRVbbr0ShyYM0U/sendVideo?chat_id=6849625315"
          
